-- Fundação aditiva de solicitações de aprovação de preço abaixo do mínimo.
CREATE TABLE `order_price_approval_requests` (
  `id` CHAR(36) NOT NULL,
  `status` ENUM('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED', 'SUPERSEDED', 'EXPIRED', 'CONSUMED') NOT NULL DEFAULT 'PENDING',
  `requested_by_user_id` CHAR(36) NOT NULL,
  `requested_by_name_snapshot` VARCHAR(120) NOT NULL,
  `requested_by_email_snapshot` VARCHAR(254) NOT NULL,
  `customer_id` CHAR(36) NOT NULL,
  `customer_code_snapshot` VARCHAR(20) NOT NULL,
  `customer_name_snapshot` VARCHAR(180) NOT NULL,
  `customer_class_id_snapshot` CHAR(36) NULL,
  `customer_class_code_snapshot` VARCHAR(64) NULL,
  `customer_class_name_snapshot` VARCHAR(100) NULL,
  `customer_segment_id_snapshot` CHAR(36) NULL,
  `customer_segment_code_snapshot` VARCHAR(64) NULL,
  `customer_segment_name_snapshot` VARCHAR(100) NULL,
  `justification` VARCHAR(2000) NOT NULL,
  `content_hash` CHAR(64) NOT NULL,
  `hash_version` SMALLINT UNSIGNED NOT NULL,
  `total_quantity` DECIMAL(15, 4) NOT NULL,
  `minimum_total_amount` DECIMAL(25, 4) NOT NULL,
  `requested_total_amount` DECIMAL(25, 4) NOT NULL,
  `exception_amount` DECIMAL(25, 4) NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `requested_at` DATETIME(3) NOT NULL,
  `reviewed_by_user_id` CHAR(36) NULL,
  `reviewed_by_name_snapshot` VARCHAR(120) NULL,
  `reviewed_by_email_snapshot` VARCHAR(254) NULL,
  `review_note` VARCHAR(2000) NULL,
  `reviewed_at` DATETIME(3) NULL,
  `approved_until` DATETIME(3) NULL,
  `consumed_order_id` CHAR(36) NULL,
  `consumed_at` DATETIME(3) NULL,
  `version` INT UNSIGNED NOT NULL DEFAULT 1,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,

  UNIQUE INDEX `opar_requester_idempotency_uq` (`requested_by_user_id`, `idempotency_key`),
  UNIQUE INDEX `order_price_approval_requests_consumed_order_id_key` (`consumed_order_id`),
  INDEX `order_price_approval_requests_status_requested_at_idx` (`status`, `requested_at`),
  INDEX `opar_requester_status_requested_idx` (`requested_by_user_id`, `status`, `requested_at`),
  INDEX `order_price_approval_requests_customer_id_requested_at_idx` (`customer_id`, `requested_at`),
  INDEX `opar_reviewer_reviewed_idx` (`reviewed_by_user_id`, `reviewed_at`),
  INDEX `order_price_approval_requests_content_hash_idx` (`content_hash`),
  CONSTRAINT `order_price_approval_requests_non_negative_totals_check`
    CHECK (`total_quantity` > 0 AND `minimum_total_amount` >= 0 AND `requested_total_amount` >= 0 AND `exception_amount` >= 0),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `order_price_approval_items` (
  `id` CHAR(36) NOT NULL,
  `approval_request_id` CHAR(36) NOT NULL,
  `line_number` SMALLINT UNSIGNED NOT NULL,
  `kind` ENUM('STANDALONE_PRODUCT', 'KIT') NOT NULL,
  `requires_approval` BOOLEAN NOT NULL,
  `source_product_id` CHAR(36) NULL,
  `source_kit_id` CHAR(36) NULL,
  `source_calculation_version_id` CHAR(36) NULL,
  `source_price_list_id` CHAR(36) NOT NULL,
  `source_price_list_version_id` CHAR(36) NOT NULL,
  `source_price_list_code_snapshot` VARCHAR(64) NOT NULL,
  `source_price_list_name_snapshot` VARCHAR(120) NOT NULL,
  `source_price_list_type_snapshot` VARCHAR(40) NOT NULL,
  `source_price_list_version_snapshot` INT UNSIGNED NOT NULL,
  `source_calculation_version_snapshot` INT UNSIGNED NULL,
  `minimum_order_quantity_snapshot` INT UNSIGNED NULL,
  `maximum_order_quantity_snapshot` INT UNSIGNED NULL,
  `price_reference_snapshot` VARCHAR(20) NOT NULL,
  `code_snapshot` VARCHAR(32) NOT NULL,
  `description_snapshot` VARCHAR(255) NOT NULL,
  `reference_snapshot` VARCHAR(120) NULL,
  `unit_snapshot` VARCHAR(30) NULL,
  `quantity` DECIMAL(15, 4) NOT NULL,
  `reference_unit_price` DECIMAL(15, 4) NOT NULL,
  `minimum_unit_price` DECIMAL(15, 4) NOT NULL,
  `negotiated_unit_price` DECIMAL(15, 4) NOT NULL,
  `minimum_subtotal` DECIMAL(25, 4) NOT NULL,
  `negotiated_subtotal` DECIMAL(25, 4) NOT NULL,
  `exception_unit_amount` DECIMAL(15, 4) NOT NULL,
  `exception_total_amount` DECIMAL(25, 4) NOT NULL,
  `ipi_rate` DECIMAL(7, 4) NULL,
  `icms_rate` DECIMAL(7, 4) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

  UNIQUE INDEX `order_price_approval_items_approval_request_id_line_number_key` (`approval_request_id`, `line_number`),
  INDEX `order_price_approval_items_source_product_id_idx` (`source_product_id`),
  INDEX `order_price_approval_items_source_kit_id_idx` (`source_kit_id`),
  INDEX `order_price_approval_items_source_calculation_version_id_idx` (`source_calculation_version_id`),
  INDEX `order_price_approval_items_source_price_list_id_idx` (`source_price_list_id`),
  INDEX `order_price_approval_items_source_price_list_version_id_idx` (`source_price_list_version_id`),
  CONSTRAINT `order_price_approval_items_line_number_check` CHECK (`line_number` > 0),
  CONSTRAINT `order_price_approval_items_quantity_check` CHECK (`quantity` > 0),
  CONSTRAINT `order_price_approval_items_non_negative_values_check`
    CHECK (`reference_unit_price` >= 0 AND `minimum_unit_price` >= 0 AND `negotiated_unit_price` >= 0 AND `minimum_subtotal` >= 0 AND `negotiated_subtotal` >= 0 AND `exception_unit_amount` >= 0 AND `exception_total_amount` >= 0),
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `order_price_approval_requests`
  ADD CONSTRAINT `order_price_approval_requests_requested_by_user_id_fkey` FOREIGN KEY (`requested_by_user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_requests_reviewed_by_user_id_fkey` FOREIGN KEY (`reviewed_by_user_id`) REFERENCES `users`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_requests_customer_id_fkey` FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_requests_consumed_order_id_fkey` FOREIGN KEY (`consumed_order_id`) REFERENCES `orders`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE `order_price_approval_items`
  ADD CONSTRAINT `order_price_approval_items_approval_request_id_fkey` FOREIGN KEY (`approval_request_id`) REFERENCES `order_price_approval_requests`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_items_source_product_id_fkey` FOREIGN KEY (`source_product_id`) REFERENCES `products`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_items_source_kit_id_fkey` FOREIGN KEY (`source_kit_id`) REFERENCES `kits`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_items_source_calculation_version_id_fkey` FOREIGN KEY (`source_calculation_version_id`) REFERENCES `calculation_versions`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_items_source_price_list_id_fkey` FOREIGN KEY (`source_price_list_id`) REFERENCES `price_lists`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  ADD CONSTRAINT `order_price_approval_items_source_price_list_version_id_fkey` FOREIGN KEY (`source_price_list_version_id`) REFERENCES `price_list_versions`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE;
