-- Fundação aditiva de pedidos. Nenhuma tabela existente é alterada ou removida.
CREATE TABLE `order_number_sequences` (
  `year` SMALLINT UNSIGNED NOT NULL,
  `last_number` INT UNSIGNED NOT NULL DEFAULT 0,
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`year`),
  CONSTRAINT `order_number_sequences_last_number_check` CHECK (`last_number` <= 999999)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `orders` (
  `id` CHAR(36) NOT NULL,
  `number` VARCHAR(20) NOT NULL,
  `status` ENUM('SUBMITTED', 'CANCELLED') NOT NULL DEFAULT 'SUBMITTED',
  `customer_id` CHAR(36) NOT NULL,
  `customer_code_snapshot` VARCHAR(20) NOT NULL,
  `customer_name_snapshot` VARCHAR(180) NOT NULL,
  `customer_tax_id_snapshot` CHAR(14) NULL,
  `customer_city_snapshot` VARCHAR(120) NULL,
  `customer_state_snapshot` CHAR(2) NULL,
  `customer_class_id_snapshot` CHAR(36) NULL,
  `customer_class_code_snapshot` VARCHAR(64) NULL,
  `customer_class_name_snapshot` VARCHAR(100) NULL,
  `customer_segment_id_snapshot` CHAR(36) NULL,
  `customer_segment_code_snapshot` VARCHAR(64) NULL,
  `customer_segment_name_snapshot` VARCHAR(100) NULL,
  `created_by_user_id` CHAR(36) NOT NULL,
  `created_by_name_snapshot` VARCHAR(120) NOT NULL,
  `created_by_email_snapshot` VARCHAR(254) NOT NULL,
  `note` TEXT NULL,
  `total_quantity` DECIMAL(15, 4) NOT NULL,
  `total_amount` DECIMAL(25, 4) NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `content_hash` CHAR(64) NOT NULL,
  `submitted_at` DATETIME(3) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `orders_number_key` (`number`),
  UNIQUE INDEX `orders_created_by_user_id_idempotency_key_key` (`created_by_user_id`, `idempotency_key`),
  INDEX `orders_customer_id_submitted_at_idx` (`customer_id`, `submitted_at`),
  INDEX `orders_created_by_user_id_submitted_at_idx` (`created_by_user_id`, `submitted_at`),
  INDEX `orders_status_submitted_at_idx` (`status`, `submitted_at`),
  CONSTRAINT `orders_total_quantity_check` CHECK (`total_quantity` > 0),
  CONSTRAINT `orders_total_amount_check` CHECK (`total_amount` >= 0),
  CONSTRAINT `orders_customer_id_fkey` FOREIGN KEY (`customer_id`) REFERENCES `customers` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `orders_created_by_user_id_fkey` FOREIGN KEY (`created_by_user_id`) REFERENCES `users` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `order_items` (
  `id` CHAR(36) NOT NULL,
  `order_id` CHAR(36) NOT NULL,
  `line_number` SMALLINT UNSIGNED NOT NULL,
  `kind` ENUM('STANDALONE_PRODUCT', 'KIT') NOT NULL,
  `source_product_id` CHAR(36) NULL,
  `source_kit_id` CHAR(36) NULL,
  `source_calculation_version_id` CHAR(36) NULL,
  `source_price_list_version_id` CHAR(36) NULL,
  `source_price_list_id_snapshot` CHAR(36) NOT NULL,
  `source_price_list_code_snapshot` VARCHAR(64) NOT NULL,
  `source_price_list_name_snapshot` VARCHAR(120) NOT NULL,
  `source_price_list_type_snapshot` VARCHAR(40) NOT NULL,
  `source_price_list_version_snapshot` INT UNSIGNED NOT NULL,
  `source_calculation_version_snapshot` INT UNSIGNED NULL,
  `price_reference_snapshot` VARCHAR(20) NOT NULL,
  `code_snapshot` VARCHAR(32) NOT NULL,
  `description_snapshot` VARCHAR(255) NOT NULL,
  `reference_snapshot` VARCHAR(120) NULL,
  `unit_snapshot` VARCHAR(30) NULL,
  `quantity` DECIMAL(15, 4) NOT NULL,
  `reference_unit_price` DECIMAL(15, 4) NOT NULL,
  `negotiated_unit_price` DECIMAL(15, 4) NOT NULL,
  `minimum_reference_price` DECIMAL(15, 4) NULL,
  `normal_reference_price` DECIMAL(15, 4) NULL,
  `ipi_rate` DECIMAL(7, 4) NULL,
  `icms_rate` DECIMAL(7, 4) NULL,
  `subtotal` DECIMAL(25, 4) NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_items_order_id_line_number_key` (`order_id`, `line_number`),
  INDEX `order_items_source_product_id_idx` (`source_product_id`),
  INDEX `order_items_source_kit_id_idx` (`source_kit_id`),
  INDEX `order_items_source_calculation_version_id_idx` (`source_calculation_version_id`),
  INDEX `order_items_source_price_list_version_id_idx` (`source_price_list_version_id`),
  CONSTRAINT `order_items_line_number_check` CHECK (`line_number` > 0),
  CONSTRAINT `order_items_quantity_check` CHECK (`quantity` > 0),
  CONSTRAINT `order_items_reference_price_check` CHECK (`reference_unit_price` >= 0),
  CONSTRAINT `order_items_negotiated_price_check` CHECK (`negotiated_unit_price` >= 0),
  CONSTRAINT `order_items_minimum_price_check` CHECK (`minimum_reference_price` IS NULL OR `minimum_reference_price` >= 0),
  CONSTRAINT `order_items_normal_price_check` CHECK (`normal_reference_price` IS NULL OR `normal_reference_price` >= 0),
  CONSTRAINT `order_items_subtotal_check` CHECK (`subtotal` >= 0),
  CONSTRAINT `order_items_ipi_rate_check` CHECK (`ipi_rate` IS NULL OR (`ipi_rate` >= 0 AND `ipi_rate` <= 100)),
  CONSTRAINT `order_items_icms_rate_check` CHECK (`icms_rate` IS NULL OR (`icms_rate` >= 0 AND `icms_rate` <= 100)),
  CONSTRAINT `order_items_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `order_items_source_product_id_fkey` FOREIGN KEY (`source_product_id`) REFERENCES `products` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `order_items_source_kit_id_fkey` FOREIGN KEY (`source_kit_id`) REFERENCES `kits` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `order_items_source_calculation_version_id_fkey` FOREIGN KEY (`source_calculation_version_id`) REFERENCES `calculation_versions` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `order_items_source_price_list_version_id_fkey` FOREIGN KEY (`source_price_list_version_id`) REFERENCES `price_list_versions` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `order_email_deliveries` (
  `id` CHAR(36) NOT NULL,
  `order_id` CHAR(36) NOT NULL,
  `status` ENUM('PENDING', 'PROCESSING', 'ACCEPTED', 'DELIVERED', 'FAILED', 'BOUNCED') NOT NULL DEFAULT 'PENDING',
  `to_recipients` JSON NOT NULL,
  `from_address` VARCHAR(254) NOT NULL,
  `from_name` VARCHAR(120) NULL,
  `reply_to` VARCHAR(254) NULL,
  `template_version` VARCHAR(32) NOT NULL,
  `idempotency_key` VARCHAR(128) NOT NULL,
  `content_hash` CHAR(64) NOT NULL,
  `provider` VARCHAR(64) NULL,
  `provider_message_id` VARCHAR(255) NULL,
  `attempt_count` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  `next_attempt_at` DATETIME(3) NOT NULL,
  `reservation_token` VARCHAR(64) NULL,
  `processing_started_at` DATETIME(3) NULL,
  `reservation_expires_at` DATETIME(3) NULL,
  `public_error` VARCHAR(255) NULL,
  `technical_error_code` VARCHAR(80) NULL,
  `accepted_at` DATETIME(3) NULL,
  `delivered_at` DATETIME(3) NULL,
  `failed_at` DATETIME(3) NULL,
  `bounced_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `order_email_deliveries_idempotency_key_key` (`idempotency_key`),
  INDEX `order_email_deliveries_status_next_attempt_at_idx` (`status`, `next_attempt_at`),
  INDEX `order_email_deliveries_status_reservation_expires_at_idx` (`status`, `reservation_expires_at`),
  INDEX `order_email_deliveries_order_id_created_at_idx` (`order_id`, `created_at`),
  INDEX `order_email_deliveries_provider_provider_message_id_idx` (`provider`, `provider_message_id`),
  CONSTRAINT `order_email_deliveries_order_id_fkey` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
